#!/bin/sh -e
#
# ----------------------------------------------------------------------
# md-to-man
# ----------------------------------------------------------------------

. ./defs.sh

redo-ifchange md2man.py
if ./md2man.py </dev/null >/dev/null
then
	./md2man.py $2.md.tmp | grep -v '\.IP "   " 3'
else
	echoerr "[ md-to-man: skipping $1: missing python modules ]"
	echoerr "[ try this: sudo easy_install markdown BeautifulSoup ]"
fi
