#!/bin/sh -e

# ----------------------------------------------------------------------
# warn
# ----------------------------------------------------------------------

if ! ./md2man.py </dev/null >/dev/null
then
  echo '+------------------------------------------------------------------+'
  echo '|                        *** WARNING ***                           |'
  echo '+------------------------------------------------------------------+'
  echo '|                                                                  |' 
  echo '| The Python modules markdown and BeautifulSoup are not available. |'
  echo '| Therefore, the man pages have not been generated.                |'
  echo '| To generate the man pages, try this:                             |'
  echo '|                                                                  |' 
  echo '|   easy_install markdown BeautifulSoup                            |'
  echo '|   ./do all                                                       |'
  echo '|                                                                  |' 
  echo '+------------------------------------------------------------------+'
fi
