#!/bin/sh -e

# ----------------------------------------------------------------------
# install
# ----------------------------------------------------------------------

. ./defs.sh

vars_require_set LIBDIR

rm -f $LIBDIR/sh
evald $INSTALL -d $LIBDIR
evald cp -R sh $LIBDIR/sh
