#!/bin/sh -e

# ----------------------------------------------------------------------
# install
# Install redo lib files
# ----------------------------------------------------------------------

. ./defs.sh

vars_require_set INSTALL LIBDIR

evald $INSTALL -d $LIBDIR

for py in *.py
do
	evald $INSTALL -m 0644 $py $LIBDIR/$py
done

subdir_commands install

evald python -mcompileall $LIBDIR
