#!/bin/sh -e

# ----------------------------------------------------------------------
# install
# Install redo command implementations
# ----------------------------------------------------------------------

. ./defs.sh

vars_require_set INSTALL LIBDIR

evald $INSTALL -d $LIBDIR

for py in *.py
do
	evald $INSTALL -m 0644 $py $LIBDIR/$py
done
